UserStories/UserStories.Web/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UserStories.Business.Managers;
using UserStories.Web.Models;
using UserStories.Web.Helpers;

namespace UserStories.Web.Controllers
{
    public class GroupController : BaseController
    {
        public ActionResult Groups()
        {
            return View();
        }
        public ActionResult AddNewGroup()
        {
            return PartialView("_AddNewGroup");
        }
        public JsonResult GetGroupInfo()
        {
            using (GroupManager manager = new GroupManager(UserId))
            {
                try
                {
                    var data = manager.GetGroups();
                    List<GroupInfoModel> model = new List<GroupInfoModel>();
                    data.ForEach(v =>
                    {
                        model.Add(v.ToGroupInfoModel());
                    });
                    return Json(model, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    manager.ErrorLog(ex);
                    return Json(new { ErrorMessage = ex.Message }, JsonRequestBehavior.AllowGet);
                }
            }
        }
        public JsonResult SaveGroup(GroupModel model)
        {
            using (GroupManager manager = new GroupManager(UserId))
            {
                try
                {
                    bool isSave = manager.InsertOrUpdateGroup(model.ToGroup());
                    if (!isSave)
                        return Json(new { ErrorMessage = "Can't save group. Please try again." }, JsonRequestBehavior.AllowGet);

                    return Json(new { }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    manager.ErrorLog(ex);
                    return Json(new { ErrorMessage = ex.Message }, JsonRequestBehavior.AllowGet);
                }
            }
        }
    }
}

UserStories/UserStories.Web/Controllers/StoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UserStories.Business.Managers;
using UserStories.Web.Models;
using UserStories.Web.Helpers;

namespace UserStories.Web.Controllers
{
    public class StoryController : BaseController
    {
        public ActionResult Stories()
        {
            return View();
        }
        public ActionResult AddNewStories()
        {
            return PartialView("_AddNewStories");
        }
        public ActionResult ViewStory()
        {
            return PartialView("_ViewStory");
        }
        public JsonResult GetStories()
        {
            using (StoryManager manager = new StoryManager(UserId))
            {
                try
                {
                    List<StoryExtendedDataModel> storyModel = new List<StoryExtendedDataModel>();
                    var result = manager.GetStories();
                    result.ForEach(item =>
                    {
                        storyModel.Add(item.ToStoryExtendedDataModel());
                    });
                    return Json(storyModel, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    manager.ErrorLog(ex);
                    return Json(new { ErrorMessage = ex.Message }, JsonRequestBehavior.AllowGet);
                }
            }
        }
        public JsonResult SaveStory(StoryModel model)
        {
            using (StoryManager manager = new StoryManager(UserId))
            {
                try
                {
                    var isSaved = manager.InsertOrUpdateStory(model.ToStory());
                    if (!isSaved)
                        return Json(new { ErrorMessage = "Can't save group. Please try again." }, JsonRequestBehavior.AllowGet);
                    return Json(new { }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    manager.ErrorLog(ex);
                    return Json(new { ErrorMessage = ex.Message }, JsonRequestBehavior.AllowGet);
                }
            }
        }
    }
}

UserStories/UserStories.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - My ASP.NET MVC Application</title>
    <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
    <meta name="viewport" content="width=device-width" />
    @Styles.Render("~/Content/css")    
    @Styles.Render("~/Content/kendo/css")    
    @Scripts.Render("~/bundles/jquery")
</head>
<body>
    <header>
        <div class="content-wrapper">
            <div class="float-right">
                @if (Request.IsAuthenticated && UserStories.Web.Utilities.SessionManager.UserInfo != null && UserStories.Web.Utilities.SessionManager.UserInfo.Id != 0)
                {
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Groups", "Groups", "Group")</li>
                            <li>@Html.ActionLink("Stories", "Stories", "Story")</li>
                        </ul>
                    </nav>
                }
            </div>
        </div>
    </header>
    <div id="body">
        @RenderSection("featured", required: false)
        <section class="content-wrapper main-content clear-fix">
            @RenderBody()
        </section>
    </div>
    <footer class="story_footer">
        <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
    </footer>    
    @Scripts.Render("~/bundles/kendo")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("scripts", required: false)
</body>
</html>