UserStories/UserStories.Web/Controllers/CommonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UserStories.Business.Managers;
using UserStories.Web.Models;

namespace UserStories.Web.Controllers
{
    public class CommonController : BaseController
    {
        [HttpGet]
        public JsonResult GetGroups()
        {
            using (GroupManager manager = new GroupManager(UserId))
            {
                List<SimpleModel> model = new List<SimpleModel>();
                var dbModel = manager.GetGroups();
                foreach (var item in dbModel)
                {
                    model.Add(new SimpleModel
                    {
                        Text = item.Name,
                        Value = item.Id                        
                    });
                }
                return Json(model, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

UserStories/UserStories.Web/Controllers/StoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UserStories.Business.Managers;
using UserStories.Web.Models;
using UserStories.Web.Helpers;

namespace UserStories.Web.Controllers
{
    public class StoryController : BaseController
    {
        public ActionResult Stories()
        {
            return View();
        }
        public ActionResult AddNewStories()
        {
            return PartialView("_AddNewStories");
        }
        public ActionResult ViewStory()
        {
            return PartialView("_ViewStory");
        }
        public JsonResult GetStories()
        {
            using (StoryManager manager = new StoryManager(UserId))
            {
                try
                {
                    List<StoryExtendedDataModel> storyModel = new List<StoryExtendedDataModel>();
                    var result = manager.GetStories();
                    result.ForEach(item =>
                    {
                        storyModel.Add(item.ToStoryExtendedDataModel());
                    });
                    return Json(storyModel, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    manager.ErrorLog(ex);
                    return Json(new { ErrorMessage = ex.Message }, JsonRequestBehavior.AllowGet);
                }
            }
        }
        public JsonResult SaveStory(StoryModel model)
        {
            using (StoryManager manager = new StoryManager(UserId))
            {
                try
                {
                    var isSaved = manager.InsertOrUpdateStory(model.ToStory());
                    if (!isSaved)
                        return Json(new { ErrorMessage = "Can't save group. Please try again." }, JsonRequestBehavior.AllowGet);
                    return Json(new { }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    manager.ErrorLog(ex);
                    return Json(new { ErrorMessage = ex.Message }, JsonRequestBehavior.AllowGet);
                }
            }
        }
    }
}

UserStories/UserStories.Web/Views/Story/Stories.cshtml
@{
    ViewBag.Title = "Stories";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="addnewStoryWindow" style="display:none"></div>
<div id="listStories">
    <div class="demo-section k-content wide">
        <button class="k-button k-button-icontext k-add-button" id="addnewStory"><span class="k-icon k-add"></span>Add new record</button>
        <div id="listView"></div>
        <div id="pager" class="k-pager-wrap"></div>
    </div>
</div>
@Scripts.Render("~/bundles/story")
<script type="text/x-kendo-template" id="template" style="padding:5px;">
    <div class=" k-group" style="padding:5px; border:black solid 1px" id="editStory">
    <h2>#:Title#</h2>
    <p> Created By #: User.FullName#</p>
    <p> PostedOn #: $storyManager.parseJsonDate(PostedOn)#</p>
    <div class="edit-buttons">
        <a class="k-button" href="\\#" onclick="$storyManager.clickEdit('#:StoryId#')"><span class="k-icon k-edit"></span></a>
        <a class="k-button" href="\\#" onclick="$storyManager.clickView('#:StoryId#')">Details</a>
    </div>
    </div>
</script>
<script>
    $(document).ready(function () {
        var storyParams = {
            getStoryUrl: '@Url.Action("GetStories", "Story")',
            saveStoryUrl: '@Url.Action("SaveStory", "Story")',
            addNewStoryUrl: '@Url.Action("AddNewStories", "Story")',
            getGroupUrl : '@Url.Action("GetGroups", "Common")'
        };
        var _storyManager = new storyManager(storyParams);
    });
</script>

UserStories/UserStories.Web/Views/Story/_AddNewStories.cshtml
<div id="storyForm">
    <input type="hidden" name="StoryId" id="hdnStoryId" />
    <ul class="ul-group">
        <li>
            <p class="bold" style="margin: 2px 0px 0 0;">Title</p>
            <input type="text" id="txtTitle" name="Title" class="k-textbox" required="" style="width:350px" data-required-msg="Title is required" />
            <span class="k-invalid-msg" data-for="Title"></span>
        </li>
        <li>
            <p class="bold" style="margin: 2px 0px 0 0">PostedOn</p>
            <input id="dpPostedOn" name="PostedOn" required="" style="width:350px" data-required-msg="PostedOn is required" />
            <span class="k-invalid-msg" data-for="PostedOn"></span>
        </li> 
        
        <li style="width: 350px; float: left;">
            <p class="bold" style="float: left; margin: 2px 0px 0 0; width: 155px; text-align: left;">Groups</p>
            <input type="hidden" name="Groups" id="hdnGroupId" />
            <div style="width: 350px">
                <select id="selGroupId" style="max-height:50px; overflow-y:scroll; width:95%" name="GroupId" required="" data-required-msg="Group is required"></select>
                <span class="k-invalid-msg" data-for="GroupId"></span>
            </div>
        </li>
            
        <li>
            <p class="bold" style="margin: 2px 0px 0 0">Description</p>
            <textarea id="txaDescription" name="Description" maxlength="400" class="k-textbox" style="width: 90%; margin-top: 0px" required="" data-required-msg="Description is required"></textarea>
            <span class="k-invalid-msg" data-for="Description"></span>
        </li>
        <li>
            <p class="bold" style="margin: 2px 0px 0 0">Content</p>
            <textarea id="txaContent" name="Content" maxlength="400" class="k-textbox" style="width: 90%; margin-top: 0px" required="" data-required-msg="Description is required"></textarea>
            <span class="k-invalid-msg" data-for="Content"></span>
        </li>
        <li style="width: 250px; margin-top: 20px">
            <button id="btnAddStory" type="button" class="k-button"><span>Save</span></button>
            <button id="btnCancel" type="button" class="k-button"><span>Cancel</span></button>
        </li>
    </ul>
</div>